### ISSUE TITLE
How to build on Ubuntu 22.04 ?

### ISSUE THREAD

**Issue by github-userx** [StephaneCouturier/Katalog#445]
https://github.com/StephaneCouturier/Katalog/wiki/Build-from-sources

Operating System:  Ubuntu-Mate 22.04

Have done the following so far:

```
sudo apt install kde-plasma-desktop
sudo apt install build-essential make
```

Not sure how to install Qt5.15 and how to follow https://community.kde.org/Get_Involved/development/Install_the_dependencies

**Comment by github-userx** [comment]
And do I understand it correctly that for the Linux portable version a .sh file is the app starter?

**Comment by StephaneCouturier** [comment]
Hi Archivist,

Sincere apologies, the page [Build from Source](https://github.com/StephaneCouturier/Katalog/wiki/Build-from-sources) was outdated. I just updated it.

I started Katalog using some KF5 libraries but faced difficulties for the compilation on Windows and the porting from Qt5 to Qt6. 
As of today and since [version 1.16](https://github.com/StephaneCouturier/Katalog/releases/tag/v1.16), Katalog is only using Qt6 and does not require KF5.

So just install Qt from their website and you should be able to compile the code.
I hope this will be easier for you.

**Comment by StephaneCouturier** [comment]
And yes, the .sh is the app starter, which should enable running Katalog on Linux without installing Qt6 libraries.
I am aware that there are some limitations to it, gcc libraries are not included and the system needs to be recent enough to have the right version.
